In [1]:
import pandas as pd

In [2]:
df1=pd.read_csv("LD DA 1.csv").drop(columns=['Label'])
df1=df1[df1['subreddit'].isin(['Anxiety', 'depression'])]
df1

,score,selftext,subreddit,title
0,1.0,Tried to watch this documentary “anxious Ameri...,Anxiety,Do people get over anxiety?
1,1.0,"i’m currently laying in bed wide awake, feelin...",Anxiety,does anyone else have this big fear of suddenl...
2,2.0,Second time trying weed. First time felt close...,Anxiety,3 hour long panic attack after trying weed
3,1.0,"I am not posting this for me, but rather for m...",Anxiety,Please leave in the comments ANYTHING that has...
4,1.0,21 year old male been dealing with anxiety eve...,Anxiety,Alcohol induced
...,...,...,...,...
195,1.0,I hate nothing about my life because I’m suppo...,depression,I’m tired of pretending like everything is okay
196,1.0,"ive been felling like this since i was 16, im ...",depression,"hey guys, help"
197,1.0,i thought getting a cat would make me feel bet...,depression,now what
198,1.0,"Hay Guys\nHow can I bet happy, when i'm depres...",depression,What should I do?
199,1.0,I don’t have anymore energy to keep going. I’m...,depression,I hope I don’t wake up in the morning

In [3]:
df2=pd.read_csv("LD EL1.csv").drop(columns=['Label','CAT 1'])
df2=df2[df2['subreddit'].isin(['Anxiety', 'depression'])]
df2

,score,selftext,subreddit,title
0,1,Of Covid-19. Of 2021. Of not getting the vacci...,Anxiety,I'm scared
1,1,"i feel like im losing my mind, my health anxie...",Anxiety,experiencing fear so visceral i unlocked memor...
2,1,This year I’ve realized I really fear death. M...,Anxiety,Fear of dying significantly deteriorating my q...
3,1,Hiya~ There have been a couple teenagers at wo...,Anxiety,I’ve been harassed at work for a couple months...
4,1,"I need some advice. I have anxiety, and I have...",Anxiety,Why do I feel like I am constantly dying ?
...,...,...,...,...
195,1,Since I was 6 my parents let their stress and...,depression,Children's life isn't something that is used t...
196,1,when i was 5 my father left and i watched he ...,depression,father
197,1,Im not here to ask for help nor do I think any...,depression,"I just want to write, it helps me think"
198,1,Putting this into the void.. I need to get som...,depression,Not sure what to do
199,1,I'm a 14-year-old kid with autism ADHD PTSD an...,depression,The life of an autistic child

In [4]:
df3=pd.read_csv("LD PF1.csv").drop(columns=['Label','CAT 1'])
df3=df3[df3['subreddit'].isin(['Anxiety', 'depression'])]
df3

,score,selftext,subreddit,title
0,1,A very minor thing happened which triggered my...,Anxiety,I lost the strength in me
1,1,"Hi, I am a 52-year-old female who has been dea...",Anxiety,Looking to be supported and support others lik...
2,1,"I know it’s just the season, it everything so...",Anxiety,I know it’s just the season.
3,1,I hold a very close connection to my interests...,Anxiety,I hate talking about my interests with people ...
4,1,Have you ever been triggered just before bed? ...,Anxiety,Anxiety Tonight
...,...,...,...,...
129,1,I wish I was normal. I wish I had a better lif...,depression,I wish I weren't such a loser
130,1,I have been dealing with the symptom of depres...,depression,Idk what to do
131,1,"We've all been there before, right? Feeling g...",depression,I've been feeling too good about some stuff re...
132,1,I have always been known as a happy person to ...,depression,I don't care if I die. Everything's going back...
133,1,All I wanted to do was comfort my boyfriend's ...,depression,Brain fog sucks. I can't think straight or mem...

In [5]:
df4=pd.read_csv("LD TS 1.csv").drop(columns=['Label','CAT 1'])
df4=df4[df4['subreddit'].isin(['Anxiety', 'depression'])]
df4

,score,selftext,subreddit,title
0,1,So my therapist recommended to me that I shoul...,Anxiety,My story of anxiety and an emotionally abusive...
1,1,Hey all! I'd like to start this thread to mayb...,Anxiety,How do you fill your empty cup?
2,1,When does it come? I made so many silly posts ...,Anxiety,Im high and I think I realized what I’ve been ...
3,1,I've been working at a job (~6 months so far) ...,Anxiety,Feeling down because of a customer at work
4,1,Excuse me ma'am im literally hyperventilating ...,Anxiety,"""Your anxiety cant be an excuse"""
...,...,...,...,...
104,1,I started losing weight when I started dating ...,depression,No appetite
105,1,i’ve been feeling super depressed lately due t...,depression,loneliness
106,1,"Last year, at the recommendation of my psychia...",depression,Never going to the fucking hospital again
107,1,Currently I’m 25 living and working in my fath...,depression,Being stuck in my room all day is crushing my ...
108,1,\n\nHello there I am too confused about how to...,depression,IS HAVING RELATIONSHIP WITH FIRST COUSIN SIN ?...

In [6]:
df5=pd.read_csv("anijun22.csv").drop(columns=['timestamp','author','Unnamed: 0','created_utc'])
df5

,score,selftext,subreddit,title
0,1,There's this guy that I like. I could tell tha...,Anxiety,Did he miss me? Or did he just feel bad?
1,1,Sometimes it’s hard to sit and realise the thi...,Anxiety,Can’t go to my graduation because of anxiety
2,1,"I was having horrible, pretty regular heart pa...",Anxiety,Heart palpitations stop?
3,1,I decided to give k-health a try as I had crip...,Anxiety,Am I on the right path?
4,1,Just had a 24hr monitor show 4000 pvc’s in a d...,Anxiety,4000 heart skips (pvc) a day for past month
...,...,...,...,...
7360,1,I want to start taking heavy drugs to deal wit...,Anxiety,Everyone hates me
7361,1,I’m constantly self conscious about people loo...,Anxiety,I have terrible anxiety about my appearance.
7362,1,So I notice that I am sleeping a lot more too ...,Anxiety,How do I fix this?
7363,1,\nFor the past two weeks every night I have be...,Anxiety,I can’t sleep
7364,1,I recently got into a US master's program and ...,Anxiety,I need someone to tell me I'm overthinking this

In [7]:
df6=pd.read_csv("anxiaug22.csv").drop(columns=['timestamp','author','Unnamed: 0','created_utc'])
df6

,score,selftext,subreddit,title
0,1,I have had this for probably about 8 years now...,Anxiety,Anyone else get daily tension headaches?
1,1,Any suggestions to handle the severe and rapid...,Anxiety,Gut response to Anxiety
2,1,My dr seems really reluctant to prescribe some...,Anxiety,Medication advice
3,1,I’ve been doing so well. But recently went thr...,Anxiety,I had another setback.
4,1,"I'm 30 years old, and I've been hospitalized 1...",Anxiety,"I woke up in the hospital on Friday morning, n..."
...,...,...,...,...
7645,1,NaN,Anxiety,Anybody else feel like they just wanna stay in...
7646,1,What are some of your best ways to cope with s...,Anxiety,Best ways to cope
7647,1,"Hi all, i need a help from you guys. I have a ...",Anxiety,Pls help to find the cause of my symptom.
7648,1,"Been dealing with lots of stress lately, and r...",Anxiety,Has Xanax made anyone’s anxiety worse?
7649,1,Today is my moms birthday dinner and a huge tr...,Anxiety,Moms birthday dinner-huge trigger present(father)

In [8]:
df7=pd.read_csv("anxijul20.csv").drop(columns=['timestamp','author','Unnamed: 0','created_utc'])
df7

,score,selftext,subreddit,title
0,1,When does it end??,Anxiety,I get super anxious which makes my throat tigh...
1,1,Anyone else's anxiety skyrocket when you have ...,Anxiety,Super nervous anytime I have to ask for time off
2,1,What’s wrong with virtual church? My church wh...,Anxiety,Covid And church
3,1,"Hi all,\n\nI've been suffering with moderate t...",Anxiety,Experience with Combination Medication
4,1,It takes me ages to get through a book because...,Anxiety,Does anyone else find it hard to read books wh...
...,...,...,...,...
6691,1,"I'm not sure this belongs in Anxiety, but I do...",Anxiety,I've always been dumb as a brick. Why is that?
6692,1,When I’m stressed about something I can’t get ...,Anxiety,Does this sound like just bad anxiety or does ...
6693,1,I have been suffering from anxiety for a long ...,Anxiety,I can't stand my wife's family and recently I ...
6694,1,My psyche prescribed me Gabapentin - Ive moved...,Anxiety,"Anyone else ""immune"" to Gabapentin?"
6695,1,My social anxiety order is getting in between ...,Anxiety,Socially anxious lifter.

In [9]:
df8=pd.read_csv("anxijun21.csv").drop(columns=['timestamp','author','Unnamed: 0','created_utc'])
df8

,score,selftext,subreddit,title
0,1,ive smoked at least 30 cigs in my life and hav...,Anxiety,worried about cancer
1,1,I feel like I can't transition into 'automatic...,Anxiety,How to get over fear that I'll lose the abilit...
2,1,By this I mean I watch stuff like cold cases b...,Anxiety,Hate not being able to watch scary or unsettli...
3,1,I'm not diagnosed with anxiety but I'm startin...,Anxiety,Anyone get anxiety about choosing an item to b...
4,1,I have really bad anxiety due to something tha...,Anxiety,All my friends hate me in a way and now I'm sc...
...,...,...,...,...
7630,1,What is the weirdest physical symptom/side eff...,Anxiety,Weirdest physical symptom of anxiety?
7631,1,Because I skipped school for half a year I got...,Anxiety,I'm an introvert
7632,1,"(Originally I made this for the ""Advice Needed...",Anxiety,Destructive thoughts popping up
7633,0,I have been struggling with pain for a few yea...,Anxiety,Doctor's Visit Anxiety
7634,1,"My eyelid has been twitching for 3 weeks, ive ...",Anxiety,Eyelid twitch due to bad vision possible+

In [10]:
df9=pd.read_csv("anxinov21.csv").drop(columns=['timestamp','author','Unnamed: 0','created_utc'])
df9

,score,selftext,subreddit,title
0,1,"I'm not sure if it is anxiety or what, but lat...",Anxiety,I'm looking for advice
1,2,"Hi:)\n\nI’m not sure if this is anxiety, but I...",Anxiety,Difficulty connecting?
2,1,I’m finishing my first semester at college in ...,Anxiety,Anxious and depressed about my mom moving away...
3,1,I’m just sitting in the airport now waiting fo...,Anxiety,I had a panic attack and couldnt get on the pl...
4,1,"I’m really freaking out. I don’t know why, but...",Anxiety,Terrible anxiety at the thought of getting int...
...,...,...,...,...
7386,1,I have anxiety and overthinking problems and t...,Anxiety,May somebody help?
7387,1,If you could please send me any good vibes or ...,Anxiety,Send me good vibes if you can… I’m getting mar...
7388,1,So today I keep myself busy all day. I clean m...,Anxiety,Suppressing my panic attack and negative thoug...
7389,1,I had plans with someone and they blew me off ...,Anxiety,Why do I blame myself for another person's beh...
7390,1,No support on reddit here it is disappointing ...,Anxiety,No support here on reddit

In [11]:
df10=pd.read_csv("depnov21.csv").drop(columns=['timestamp','author','Unnamed: 0','created_utc'])
df10

,score,selftext,subreddit,title
0,1,[removed],depression,How do you get out of a depressive cycle
1,1,"Hello everyone,\n\nMy name is Ly, 25M. Quarter...",depression,my battle with lifelong anxiety and depression...
2,1,[removed],depression,Unfortunately nobody likes me here
3,1,[removed],depression,What’s your go to for escaping a depressive cy...
4,1,You ever just accidentally look in the mirror ...,depression,A husk
...,...,...,...,...
16205,1,I’m just sick of feeling like I’m a bother to ...,depression,Haven’t been able to see my psychologist in th...
16206,1,I fucking hate my parents. Unsupportive ass bi...,depression,I'm already dying
16207,1,i just need a safe space….i am tired and unabl...,depression,pov: it has been 5 years
16208,1,[removed],depression,I called the suicide helpline a few days ago.....
16209,1,[removed],depression,"I've been experiencing depressive feelings, bu..."

In [12]:
df11=pd.read_csv("depjun21.csv").drop(columns=['timestamp','author','Unnamed: 0','created_utc'])
df11

,score,selftext,subreddit,title
0,1,Everyone time I look in the mirror I just feel...,depression,Why am I so ugly
1,1,"The smell of the salt air, boats on parade sai...",depression,Observations of the Sublime - Sea and Sand
2,1,[removed],depression,I Want To Die On My Birthday
3,1,\nI told my doctor I think I’m depressed and w...,depression,Considering therapy
4,1,I met the guy a little over half a year ago on...,depression,A close friend of mine is suffering from extre...
...,...,...,...,...
15248,2,"When youve been hurt so much, \nYou build wall...",depression,You and them
15249,2,"idk how much longer i can last. i was bad, the...",depression,relapsed after a year
15250,2,I’ve been depressed and on medication for 6 mo...,depression,I share this and I hope I can help some people
15251,1,"Hello, I am 29 years old guy, overweight and w...",depression,Need advice!
15252,1,What I wrote below was a comment in response t...,depression,There is no time. You are either engaged or di...

In [13]:
df12=pd.read_csv("depjul20.csv").drop(columns=['timestamp','author','Unnamed: 0','created_utc'])
df12

,score,selftext,subreddit,title
0,1,There is no one in my life that actually under...,depression,I feel so alone and its all my fault..
1,1,I have a good job right now in a career that p...,depression,I get envious of things I shouldn't be envious...
2,1,Well I didn't realise how much I hate talking ...,depression,Finally pt 2
3,1,"ok so hi, i’m 21f, almost 22 at this point i’m...",depression,failure lmao
4,1,[removed],depression,[TRYING TO HELP] Insight Into Depression - Sad...
...,...,...,...,...
15775,1,"i always check up on people, they never do the...",depression,:(
15776,2,so at the beginning of this year i developed d...,depression,i need to rant so badly ( i don't expect answe...
15777,1,I was on medication and doing better (finally ...,depression,Limbo
15778,1,im getting worse every day. i make a plan to t...,depression,is depression real or am i just a pussy
15779,1,First off this has nothing to do with the viru...,depression,As time goes on I'm finding less reasons to st...

In [14]:
df13=pd.read_csv("Swjul20.csv").drop(columns=['timestamp','author','Unnamed: 0','created_utc'])
df13

,score,selftext,subreddit,title
0,1,I’m so fucking tired of this endless cycle. ...,SuicideWatch,"I’m in a psych unit, I got the help I was told..."
1,1,I will disappear,SuicideWatch,This world doesn’t deserve me
2,1,\nI really can't do this anymore. It's been go...,SuicideWatch,Intrusive thoughts getting worse
3,1,"Hi, I’ve been wanting to own a firearm for qui...",SuicideWatch,"Wanting a firearm, but don’t know if I could h..."
4,1,I work a minimum wage coffee job. I have been ...,SuicideWatch,Thinking about it at work
...,...,...,...,...
11161,1,i just have no reason to live i dont have much...,SuicideWatch,idk
11162,1,i attempted suicide last night. i took a bunch...,SuicideWatch,my mom doesn’t care that i attempted suicide.
11163,3,Will 10mg of Xanax and 750mL of woodford be en...,SuicideWatch,Callin it quits
11164,1,i keep making my relationships worse and worse...,SuicideWatch,why do i keep messing it up
11165,1,20 years old.. it’s just a normal day like any...,SuicideWatch,It’s my birthday today and just want to die.

In [15]:
df14=pd.read_csv("swjun21.csv").drop(columns=['timestamp','author','Unnamed: 0','created_utc'])
df14

,score,selftext,subreddit,title
0,1,Got my 6th LSAT score back today and it was th...,SuicideWatch,Feeling Debilitated
1,1,The thing is that I keep myself busy all the t...,SuicideWatch,Just someone who wanna die since years..
2,1,I've lost hope on improving. It doesn't matter...,SuicideWatch,I'm weak at the core
3,1,Okay so had my second therapy session yesterda...,SuicideWatch,Suicidal ideation
4,1,My dream several years ago was to pitch in the...,SuicideWatch,Does it make sense to want to kill yourself ju...
...,...,...,...,...
15816,1,[removed],SuicideWatch,How i survived seicide
15817,1,[deleted],SuicideWatch,I couldn’t do it
15818,2,I’m done. I’m a failure. I’m alone. I’m broke....,SuicideWatch,I guess I’ll just kill myself
15819,1,I never get on Facebook anymore. It's too pain...,SuicideWatch,I miss her so much...
15820,2,NaN,SuicideWatch,Going to kill myself right now made up my mind...

In [16]:
df15=pd.read_csv("swnov21.csv").drop(columns=['timestamp','author','Unnamed: 0','created_utc'])
df15

,score,selftext,subreddit,title
0,1,I spend every waking moment wanting to feel si...,SuicideWatch,I can't carry this anymore.
1,1,Maybe I won’t\n\nMaybe I will\n\nKilling mysel...,SuicideWatch,Maybe I’ll do it today
2,1,Back here in this hole again. Why does it keep...,SuicideWatch,"Me again, again."
3,1,I first started self harming when I was 13 I m...,SuicideWatch,I’m back in hell
4,1,"So far on the edge Today, yesterday was bad, b...",SuicideWatch,A cry out for help.
...,...,...,...,...
15419,1,I suffer from body dysmorphia and depression. ...,SuicideWatch,I’m planning on killing myself today.
15420,1,[removed],SuicideWatch,Suicidal because of crush
15421,1,"It's killing me slowly, I hate this gaslightin...",SuicideWatch,Narcissistic abuse
15422,1,"Last year in October, I was arrested for defen...",SuicideWatch,"Single Mom, life falling apart."
15423,1,[removed],SuicideWatch,Happy Halloween

In [17]:
df16=pd.read_csv("Swmar22.csv").drop(columns=['timestamp','author','Unnamed: 0','created_utc'])
df16

,score,selftext,subreddit,title
0,1,I want to see if people around me really care ...,SuicideWatch,I want to commit suicide beacuse I lost the di...
1,1,[removed],SuicideWatch,"I've been numb for so long, i can't anymore, G..."
2,1,i guess i was starting to get better. but it’s...,SuicideWatch,it’s back again.
3,1,This is my first time having these thoughts. I...,SuicideWatch,Am I suicidal?
4,1,Nothing matters and life is worthless. I'm jus...,SuicideWatch,Nothing Matters
...,...,...,...,...
14143,1,[removed],SuicideWatch,Been a laughing stock and pushed around most o...
14144,1,Please just talk..,SuicideWatch,Good morning.
14145,1,[removed],SuicideWatch,Been starting to have thoughts over recent wor...
14146,1,[removed],SuicideWatch,I was supposed to be dead a year ago. Sorry th...
14147,1,I have ptsd as the result of abuse and sexual ...,SuicideWatch,I don't want to die but I don't know how I wil...

In [18]:
dfs=[df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12,df13,df14,df15,df16]
combined_df = pd.concat(dfs, ignore_index=True)
combined_df

,score,selftext,subreddit,title
0,1.0,Tried to watch this documentary “anxious Ameri...,Anxiety,Do people get over anxiety?
1,1.0,"i’m currently laying in bed wide awake, feelin...",Anxiety,does anyone else have this big fear of suddenl...
2,2.0,Second time trying weed. First time felt close...,Anxiety,3 hour long panic attack after trying weed
3,1.0,"I am not posting this for me, but rather for m...",Anxiety,Please leave in the comments ANYTHING that has...
4,1.0,21 year old male been dealing with anxiety eve...,Anxiety,Alcohol induced
...,...,...,...,...
140998,1.0,[removed],SuicideWatch,Been a laughing stock and pushed around most o...
140999,1.0,Please just talk..,SuicideWatch,Good morning.
141000,1.0,[removed],SuicideWatch,Been starting to have thoughts over recent wor...
141001,1.0,[removed],SuicideWatch,I was supposed to be dead a year ago. Sorry th...
141002,1.0,I have ptsd as the result of abuse and sexual ...,SuicideWatch,I don't want to die but I don't know how I wil...

In [19]:
combined_df['subreddit'] = combined_df['subreddit'].str.strip().str.lower()

target_map = {
    'anxiety':    'Anxiety',
    'depression': 'Depression',
    'suicidewatch': 'SuicideWatch'
}

filtered_df = combined_df[combined_df['subreddit'].isin(target_map.keys())].copy()
filtered_df['label'] = filtered_df['subreddit'].map(target_map)

print(filtered_df['label'].value_counts())

label
SuicideWatch    56290
Depression      47119
Anxiety         36901
Name: count, dtype: int64

In [20]:
samples_per_class= 4000 

balanced_df = (
    filtered_df
    .groupby('label', group_keys=False)
    .apply(lambda x: x.sample(min(len(x), samples_per_class), random_state=42))
    .reset_index(drop=True)
)

print(balanced_df['label'].value_counts())
print(f"Total: {len(balanced_df)} rows")

label
Anxiety         4000
Depression      4000
SuicideWatch    4000
Name: count, dtype: int64
Total: 12000 rows

C:\Users\DELL\AppData\Local\Temp\ipykernel_5392\1071843748.py:6: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.sample(min(len(x), samples_per_class), random_state=42))

In [21]:
balanced_df.to_csv('dataset.csv', index=False)